theme: jekyll-theme-minimal
title: tkchoy page
description: descriptive text goes here it can be very verbose and I'm not sure why you'd want that to be the case.  What do you want? what is this going to do?  Let's see. 